---
- name: Stop and Config vhost1
  hosts: test
  become: yes
  tasks:
   - name: stop apache 
     service: name=httpd state=stopped

   - name: write apache config 
     template: src=httpd.j2 dest=/etc/httpd/conf.d/welcome.conf


- name: Stop and Config vhost2
  hosts: test2
  become: yes
  tasks:
   - name: stop apache 
     service: name=httpd state=stopped

   - name: write apache config 
     template: src=httpd.j2 dest=/etc/httpd/conf.d/welcome.conf



- name: Start vhost1
  hosts: test
  become: yes

  tasks:
   - name: start apache 
     service: name=httpd state=started

- name: Start vhost2
  hosts: test2
  become: yes

  tasks:
   - name: start apache 
     service: name=httpd state=started
